services:
  picomint-server:
    image: ghcr.io/joschisan/picomint-server:main
    container_name: picomint-server
    restart: unless-stopped
    ports:
      # Iroh endpoint
      - "8080:8080"
    volumes:
      - picomint_server_data:/data
    environment:
      - DATA_DIR=/data
      - BITCOIN_NETWORK=bitcoin
      - ESPLORA_URL=https://mempool.space/api
      - P2P_ADDR=0.0.0.0:8080
      - UI_ADDR=0.0.0.0:3000
      - UI_PASSWORD=<change-me> # REQUIRED: set a strong password
      - CLI_PORT=3030

volumes:
  picomint_server_data:
