name: 'create reminder'

permissions:
  issues: write
  pull-requests: write

on:
  issue_comment:
    types: [created, edited]

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: 👀 check for reminder
        uses: agrc/create-reminder-action@64196866d8d89ce172328d200d15afb8533b7992 # v1.1.24
